export const tables = {
  accountsDashboardReports: "accounts_db_reports",
  accountPaymentModes: "accounts_payment_modes",
  accountPaymentModeTypes: "accounts_payment_mode_types",
  accountsBankAccounts: "accounts_bank_accounts",
  additionalQuestions: "additional_questions",
  adminCommission: "admin_commission",
  adminUsers: "admin_users",
  adPerformanceReports: "ad_performance_reports",
  productOrders: "product_orders",
  adminAttendanceLog: "admin_attendance_log",
  popup_app_home: "popup_app_home",
  assessment: "assessment",
  camp72Details: "camp72_details",
  assessment_personal_details: "assessment_personal_details",
  assessment_nutrition_and_lifestyle: "assessment_nutrition_and_lifestyle",
  assessment_medical_history: "assessment_medical_history",
  assessment_24_hour_diet_recall: "assessment_24_hour_diet_recall",
  assessment_workout_details: "assessment_workout_details",
  balanceLogs: "balance_amount_log",
  billingDetails: "billing_details",
  blogPosts: "blog_posts",
  blogPostsCategory: "blog_cats",
  bnAppReminderContent: "bn_app_reminder_content",
  bnGoogleReviews: "bn_google_reviews",
  Services: "bn_services",
  all_programs_grouped: "all_programs_grouped",
  bcaTable: "bca_table",
  bnMyGoals: "bn_my_goals",
  bnMyGoalsNew: "my_goals_1",
  bnAppLinks: "bn_app_links",
  callUpdates: "call_updates",
  campDetails: "camp_details",
  campaigns: "campaigns",
  cart: "cart",
  cartItems: "cart_items",
  category: "bn_app_recipes_category",
  categoryList: "free_filler_category_list",
  bn_recipe_type: "bn_recipe_type",
  cuisine: "bn_app_recipes_cuisine",
  cities: "cities",
  clientQueries: " client_queries",
  clientStatusLogs: "client_status_change_log",
  changeOfMentor: "change_of_mentor",
  consultationLogs: "consultation_log",
  contentLikes: "content_likes",
  contentShares: "content_shares",
  countries: "countries",
  coupons: "coupons",
  crashAnalytics: "crash_analytics",
  csReminders: "cs_reminders",
  department: "department",
  dietPdfDownloadLog: "diet_pdf_download_log",
  dietSessionLog: "diet_session_log",
  drafts: "drafts",
  draftedQueries: "drafted_queries",
  dubaiConsultations: " dubai_consultations",
  dubaiWorkshops: " dubai_workshop",
  ekit: "bn_e_kit_master_new",
  faq: "faq",
  fbPost: "fb_posts",
  feedback: "feedback",
  fcm_registry: "bn_user_fcm_token",
  finalFeedback: "bn_final_feedback",
  freeFillerClicks: "free_filler_clicks",
  freeFillerData: "free_filler_data",
  freeFillerUsersData: "free_filler_users_data",
  goodMails: "good_mails",
  guides: "guide_details",
  hashtags: "bn_hashtags",
  halfTimeFeedback: "bn_halftime_feedback",
  healthIssues: "health_issues",
  healthScore: "bn_app_health_score",
  healthScoreClient: "bn_client_hs",
  halftimeFeedback: "bn_halftime_feedback",
  instPosts: "insta_posts",
  inchRecords: "inch_records",
  incentivePool: "bn_incentive_pool",
  inAppPageVisitLog: "in_app_page_visit_log",
  ingredients: "ingredients",
  bn_recipes_ingredients: "bn_recipes_ingredients",
  khyatisContent: "khyatis_content",
  leadsActivatedFeatures: "leads_activated_features",
  leadActionAssignedLog: "lead_action_assigned_log",
  leadAssignedLog: "lead_assigned_log",
  leadFeedback: "lead_feedback",
  leadEngagementLogs: "lead_engagement_logs",
  leadFollowUpLogs: "lead_follow_up_logs",
  leadSaleStatusLog: "lead_sale_status_log",
  leadStageLog: " lead_stage_log",
  leadSource: "lead_source",
  leadSourceLog: "lead_source_logs",
  leadStatus: "lead_status",
  leadStatusLog: "lead_status_log",
  leadSubSource: "lead_sub_source",
  leadSubStatus: "lead_sub_status",
  loginLogs: "login_logs",
  mentorEvents: "mentor_events",
  mentorGoals: "mentor_goals",
  mentorNotifications: "mentor_notifications",
  maintenanceMasters: "bn_maintenance_master",
  maintenanceOrderDetails: "maintenance_order_details",
  milestoneFormData: "milestone_form_data",
  notifications: "notifications",
  notificationLogs: "notification_logs",
  numbers: "numbers",
  schedulesNotifications: "scheduled_notifications",
  bnUserNotifications: "bn_user_notification",
  offers: "bn_offers",
  offersNew: "bn_offers_new",
  offerLogs: "offer_logs",
  orderLogs: "order_logs",
  officeExpenses: "office_expenses",
  officeVisit: "office_visit",
  onholdClients: "onhold_clients",
  orderDetails: "order_details",
  organizations: "organizations",
  otherLinks: "other_links",
  paymentLinks: "payment_links",
  paymentModes: "payment_mode",
  phaseLogs: "phase_logs",
  photoRecords: "photo_records",
  leadPhotoRecords: "lead_photo_records",
  prizeDetails: "prize_details",
  programCategory: "program_category",
  programDocuments: "program_documents_and_others",
  programOfferImages: "program_offer_images",
  programStatsImages: "program_stats_images",
  programsMaster: "programs_master",
  programSession: "program_session",
  program_expiry_log: "program_expiry_log",
  rawVideos: "raw_videos",
  recipe: "bn_recipe",
  recipe_type: "bn_recipe_type",
  regions: "regions",
  regionsMembers: "region_members",
  reports: "reports",
  roles: "roles",
  socialMediaAnalysis: "social_media_analysis",
  socialPost: "social_post",
  dubaiSlots: "dubai_slots",
  salesReviewNotes: "sales_review_notes",
  shopProductBrands: "shop_product_brands",
  shopProductCategories: "shop_product_categories",
  shopProductCategoryMap: "shop_product_category_map",
  shopProducts: "shop_products",
  slots: "bn_book_appointment_slots_mentor",
  specialDietPlan: "diet_special_plan",
  newSpecialDietPlan: "diet_special_plan_new",
  states: "states",
  subCategory: "bn_app_recipes_sub_category__",
  shortUrls: "short_urls",
  subOrderPrograms: "sub_orders_programs",
  successStories: "success_stories",
  dietFeedback: "diet_feedback",
  franchiseChapter: "franchise_chapter",
  franchiseInquiries: "franchise_inquiries",
  suggestedProgram: "suggested_program",
  tableText: "table_text",
  tipsVisitLog: "tip_visit_log",
  upgradeRequest: "upgrade_requests",
  users: "users",
  userDetails: "users_details",
  userDetailsCopy: "users_details",
  userDeactivationLog: "user_deactivation_logs",
  userActivityLog: "user_activity_log",
  userAppActivityLog: "user_app_activity_log",
  userMilestones: "user_milestones",
  userKeyInsight: "user_key_insight",
  userSearchLog: "user_search_log",
  teamTarget: " team_target",
  walletLog: "wallet_log",
  programExpiryLog: "program_expiry_log",
  weightRecords: "weight_records",
  weightRecordsLead: "weight_records_lead",
  dietSessionLog: "diet_session_log",
  ingredientCategory: "ingredient_category",
  ingredientChecklistRecords: "ingredient_checklist_records",
  ingredientsList: "ingredients_list",
  loginRegistrationOtp: "login_registration_otp",
  food_frequency_master: "food_frequency_master",
  user_notifications: "user_notifications",
  recipeChapters: "recipe_chapters",
  bookmarkedRecipes: "bookmarked_recipes",
  whatsappText: "whatsapp_text",
  restaurantFoodMenu: "restaurant_food_menu",
  restaurantCuisines: "restaurant_cuisines",
  restaurantCourses: "restaurant_courses",
  userRestaurantMenu: "user_restaurant_menu",
  userAlcoholMenu: "user_alcohol_menu",
  userDailyTracker: "user_daily_tracker",
  alcoholCategories: "alcohol_categories",
  product_orders: "product_orders",
  claraCategories: "clara_faq_categories_new",
  claraQnA: "clara_questions_and_answers_new",
  onHoldClientPaidService: "onhold_clients_paid_service",
  postPregnancyData: "post_pregnancy_formdata",
  whatsappAppSlots: "whatsapp_app_follow_up_slots",
  nutripreneurEnquiry: "nutripreneur_enquiries",
};

export const cloudinaryFolders = {
  blog_post: "blog_post_images",
  fbPosts: "fb_post_images",
  instaPosts: "insta_post_images",
  notification: "notification_banners",
  recipe_images: "recipes/images",
  recipe_videos: "recipes/videos",
  offers: "offer_images",
  organizations: "organization_logo",
  programMaster: "program_master_images",
  successStoryImages: "success_stories/images",
  successStoryVideos: "success_stories/videos",
  reports: "reports",
  rawVideos: "raw_videos",
  dietPdf: "diet_pdf",
  drafts: "drafts",
  recipeTypeIcon: "recipe_type_icon",
  socialPostImages: "social_post/images",
  socialPostVideos: "social_post/videos",
  programOfferImages: "program_offer_images",
  programStatsImages: "program_stats_images",
  programDocuments: "program_documents",
  queryAttachments: "query_attachments",
  dietAttachments: "diet_attachments",
};

export const productLinkMap = {
  "Baked Nippat": "https://balancenutrition.in/shop/baked-nippat",
  Quicky: "https://balancenutrition.in/shop/quicky",
  "Khatta Meetha Quicky":
    "https://balancenutrition.in/shop/khatta-meetha-quicky",
  "BN-Dark Chocolate Cookies":
    "https://balancenutrition.in/shop/dessert-cookies-chocolate",
  "Sampler Pack": "https://balancenutrition.in/shop/sampler-pack",
  "Makhana Chips": "https://balancenutrition.in/shop/makhana-chips",
};

export const redisKeys = {
  AndroidOcClients: "android_oc_clients",
  AllMaintainenceClients: "all_maintainence_clients",
  allTeams: "all_teams",
  individualTarget: "individual_target",
  assessment_clients: "assessment_clients",
  appNotUpdatedClients: "app_not_updated_clients",
  blogs: "blogs",
  categories: "categories",
  ingredients: "ingredients",
  cuisines: "cuisines",
  coupons: "coupons",
  ClientNCLICLNotFilledCount: "client_NCL_ICL_not_filled_count",
  ClientOnBreakCount: "client_on_break_count",
  ClientsBalanceDue: "client_balance_due",
  ClientsWeightReceivedDietNotSentCount:
    "client_session_weight_inch_not_updated_count",
  ClientsExpiring: "clients_expiring",
  ClientServiceCallNotDone: "client_service_call_not_done",
  ClientsWithAdvancePurchase: "clients_with_advance_purchase",
  dormantClientsCount: "dormant_clients_count",
  drafts: "drafts",
  enquiryClients: "enquiry_clients",
  fbposts: "fbposts",
  googleReviews: "google_reviews",
  goodMails: "good_mails",
  hashtags: "hashtags",
  instaPosts: "instaPosts",
  inductionCardsCount: "induction_cards_count",
  iosOcClients: "ios_oc_clients",
  orders: "orders",
  programMaster: "program_master",
  programSession: "program_session",
  recipes: "recipes",
  registerMembers: "register_members",
  sucessStories: "sucess_stories",
  card: "card-stats",
  notifications: "notifications",
  notStartedClients: "not_started_clients",
  subStatusUserCount: "sub_status_user_count",
  subStatusUserData: "sub_status_user_data",
  totalOc: "total_oc",
  programCategoryCount: "program_category_count",
  programCategoryUserData: "program_category_user_data",
};

export const leadSources = {
  0: "Others",
  1: "HS",
  2: "Website",
  3: "Social Media",
  4: "Direct Sources",
  5: "Referral",
  6: "Paid Campaigns",
};

export const leadSubSources = {
  1: "health score",
  2: "facebook",
  3: "instagram",
  4: "linkedin",
  5: "youtube",
  6: "phone enquiry",
  7: "walk in",
  8: "consultation",
  9: "whatsapp",
  10: "khyati ma'am",
  11: "zopim",
  12: "family reference",
  13: "friend's reference",
};

export const leadSourceGroups = {
  0: "Other",
  1: "HS",
  2: "Website",
  3: "Social Media",
  4: "Direct Sources",
  5: "Referral",
  6: "Paid Campaigns",
};

export const sources = {
  0: "Other",
  1: "HS Stage 1/2",
  2: "HS Stage 3/4",
  3: "Enquiry Form",
  4: "Contact Form",
  5: "Registration",
  6: "Khyati Instagram (SMO)",
  7: "Khyati Facebook (SMO)",
  8: "Khyati Youtube (SMO)",
  9: "Khyati Linkedin  (SMO)",
  10: "Khyati Twitter (SMO)",
  11: "Khyati Instagram (SME)",
  12: "Khyati Facebook (SME)",
  13: "Khyati Youtube (SME)",
  14: "Khyati Linkedin  (SME)",
  15: "Khyati Twitter (SME)",
  16: "Phone Enquiry",
  17: "Walk In",
  18: "Consultation",
  19: "Zopim",
  20: "Whatsapp",
  21: "Khyati Maam",
  22: "Referral(In App)",
  23: "Referral(Direct)",
  24: "Campaign",
  32: "Lead App",
  35: "Deloitte Group",
  36: "Dr. Reema Reference",
  37: "Dr. Shital Reference",
  38: "Dr. Beejal Reference",
  39: "Superbottoms",
  40: "Dr. Pooja Mandale Reference",
  41: "Dr. Swati Chitnis Reference",
  42: "Dr. Dhvani Zota Reference",
  43: "Force Point",
  44: "Elixir",
  45: "Spin to Win",
  46: "Perimenopause Campaign",
  47: "Mommybussiness",
  48: "Checkout",
  49: "google_search",
  50: "google_display",
  51: "meta",
  52: "Slim N Glow Challenge",
  53: "Gut Reset Challenge",
  54: "Payal Bhatia",
  55: "meta_paid_social",
  56: "BN Instagram (SMO)",
  57: "BN Facebook (SMO)",
  58: "BN Youtube (SMO)",
  59: "BN Linkedin  (SMO)",
  60: "BN Twitter (SMO)",
  61: "BN Instagram (SME)",
  62: "BN Facebook (SME)",
  63: "BN Youtube (SME)",
  64: "BN Linkedin  (SME)",
  65: "BN Twitter (SME)",
};

export const appVersions = {
  latestAndroidVersion: "5.2.58",
  latestIosVersion: "1.1.14",
};

export const videoKeys = {
  programDetailsVideo: "JlWeU-uF8Xc",
  messageFromKhyati: "Xt-hLRCGvdI",
};

export const socialLinksKhyati = {
  instagram: "https://www.instagram.com/nutritionist_khyatirupani",
  facebook: "https://www.facebook.com/balancenutrition.in",
  twitter: "https://twitter.com/BN_Tweets123",
  linkedin: "https://www.linkedin.com/in/nutritionistkhyatirupani/",
};

export const socialLinksBN = {
  instagram: "https://www.instagram.com/nutritionist_khyatirupani",
  facebook: "https://www.facebook.com/balancenutrition.in",
  twitter: "https://twitter.com/BN_Tweets123",
  linkedin: "https://www.linkedin.com/in/nutritionistkhyatirupani/",
};

export const generalConstants = {
  isForceUpdate: false,
};

export const currencyConversionRates = {
  INR: 100,
  USD: 100,
};

export const app_versions = {
  ios: "1.1.14",
  android: "5.2.58",
};

export const healthData = {
  veg_nonveg_frequency: {
    4: "None",
    7: "1 - 2 servings",
    12: "3 - 4 servings",
    14: "4 > servings",
  },
  waterFrequency: {
    4: "< 4 glasses",
    7: "4 - 6 glasses",
    12: "6 - 12 glasses",
    14: "12 > glasses",
  },
  alcoholConsumption: {
    14: "Never",
    12: "Quit since 1 year",
    7: "Occasionally",
    4: "Daily",
  },
  smokingFrequency: {
    14: "Never",
    12: "Quit since 2 years",
    7: "A few times a week",
    4: "More than 2 times a day",
  },
  activityLevels: {
    4: "Sedentary",
    7: "Lightly Active",
    12: "Moderately Active",
    14: "Very Active",
  },
  sleep: {
    7: "< 6 hrs Disturbed",
    12: "< 6 hrs Peaceful",
    14: "6 - 9 hrs",
    4: "10 > hrs",
  },
  periodsFrequency: {
    12: "Regular",
    7: "Irregular",
  },
};
export const offerTypes = {
  1: "Only Discount",
  2: "Discount + Coupon (Not Auto)",
  3: "Discount + Coupon (Auto)",
  4: "Discount + Wallet",
  5: "Discount + Wallet + Coupon (Not Auto)",
  6: "Discount + Wallet + Coupon (Auto)",
  7: "Only Coupon (Not Auto)",
  8: "Only Coupon (Auto)",
  9: "Only Wallet",
  10: "Wallet + Coupon (Not Auto)",
  11: "Wallet + Coupon (Auto)",
  12: "Either Coupon Or Wallet (With or without Discount)",
};
export const callTypes = {
  0: "Welcome Call",
  1: "Halftime Progress",
  2: "Final Feedback",
  3: "Induction Call",
  4: "Service Call",
  5: "Book by Mentor",
  6: "Change of Mentor Call",
  7: "Extra Call (Engagement)",
  8: "Pitching Call",
  9: "Bad Feedback Call",
  10: "Follow up Call",
  11: "Overdue Call (Weight / any other)",
  12: "Dormant Call",
  13: "On hold OD Call",
  14: "Follow up for Renewal Call",
  15: "Any Other Call",
  16: "Concern Call",
  17: "Head Nutritionist Concern Call",
  18: "Poor Rating Call",
  19: "Less Loss Call",
  20: "Head Nutritionist Manager Call",
  30: "Consultation Call",
  32: "Diet Feedback Call",
  33: "Pre Welcome Call",
  66: "Introduction Call",
  68: "Lead Welcome Call",
};

export const reasonNotificationMap = {
  "Start Weight Updated": 832,
  "End Session Weight Updated": 835,
  "Mid Session Weight Updated": 834,
  "Inch Added": 833,
  "End Session Inch Updated": 836,
  "Photo Added": 837,
  "Alcohol Guide Log In": 742,
  "App Filled": 746,
  "Diet Additional Questions Filled": 744,
  "Half Time Feedback": 734,
  "Half Time HS": 732,
  "Health Score": 740,
  "NAF/ICL Filled": 731,
  "Program Feedback": 735,
  "Program HS": 733,
  "Program Purchased": 736,
  "Quick Filler Guide Log In": 741,
  "Referred a friend": 737,
  "Restaurant Guide Additional Questions Filled": 745,
  "Restaurant Guide Log In": 743,
  "Tip Visited": 738,
  "Welcome Bonus": 739,
  "Signing Bonus": 1296,
  "Quiz Participation": 725,
  "Google Review": 726,
  "Mentor Bonus": 727,
  "Surprise Bonus": 728,
  "Festive Bonus": 729,
  "Birthday Bonus": 730,
};

export const marqueDetailsMap = {
  program_details_web: {
    marquee_color: "#03989F",
    text: '<p><span style="color: rgb(0, 0, 0);">         Gear up! Participate in the </span><strong style="color: rgb(0, 0, 0);">Fantastic Feb BN Wallet Quiz</strong><span style="color: rgb(0, 0, 0);"> & earn up to </span><strong style="color: rgb(0, 0, 0);">Rs.10000</strong><span style="color: rgb(0, 0, 0);"> in your BN Wallet :) Check notifications & chats regularly.       </span></p>',
    redirect_page: "program",
    params: { redirect_id: "75" },
  },
  program_details_app: {
    marquee_color: "#03989F",
    text: '<p><span style="color: rgb(0, 0, 0);">         Gear up! Participate in the </span><strong style="color: rgb(0, 0, 0);">Fantastic Feb BN Wallet Quiz</strong><span style="color: rgb(0, 0, 0);"> & earn up to </span><strong style="color: rgb(0, 0, 0);">Rs.10000</strong><span style="color: rgb(0, 0, 0);"> in your BN Wallet :) Check notifications & chats regularly.       </span></p>',
    redirect_page: "mentor_chat",
    params: { redirect_id: "6" },
  },
  home_page_app: {
    marquee_color: "#03989F",
    text: '<p><span style="color: rgb(0, 0, 0);">         Gear up! Participate in the </span><strong style="color: rgb(0, 0, 0);">Fantastic Feb BN Wallet Quiz</strong><span style="color: rgb(0, 0, 0);"> & earn up to </span><strong style="color: rgb(0, 0, 0);">Rs.10000</strong><span style="color: rgb(0, 0, 0);"> in your BN Wallet :) Check notifications & chats regularly.       </span></p>',
    redirect_page: "mentor_chat",
    params: { redirect_id: "6" },
  },
  home_page_web: {
    marquee_color: "#03989F",
    text: '<p><span style="color: rgb(0, 0, 0);">         Gear up! Participate in the </span><strong style="color: rgb(0, 0, 0);">Fantastic Feb BN Wallet Quiz</strong><span style="color: rgb(0, 0, 0);"> & earn up to </span><strong style="color: rgb(0, 0, 0);">Rs.10000</strong><span style="color: rgb(0, 0, 0);"> in your BN Wallet :) Check notifications & chats regularly.       </span></p>',
    redirect_page: "program",
    params: { redirect_id: "75" },
  },
  recipe_app: {},
  recipe_web: {},
  health_reads_app: {},
  health_reads_web: {},
  success_stories_app: {},
  success_stories_web: {},
};

export const popUpDetailsMap = {
  program_details_web: {},
  program_details_app: {},
  home_page_app: {},
  home_page_web: {},
  recipe_app: {},
  recipe_web: {},
  health_reads_app: {},
  health_reads_web: {},
  success_stories_app: {},
  success_stories_web: {},
};

export const image_guide_base_url = `www.bncleanse.com`;
export const image_guide_base_url_live = `www.balancenutrition.in`;

export const dataForPlanner = {
  due_today: {
    start_weight: ["Start Weight Not Filled Clients"],
    start_inch: ["Start Inch Not Filled Clients"],
    "10th_day_weight": ["End Weight Data"],
    "10th_day_inch": ["End Inch Data"],
    "10th_day_photo": ["End Photo Data"],
    not_started: ["Not Started Client Due Today", "Not Started Clients List"],
    balance: ["Balance Due Today"],
    onhold: ["Client Was To Become Active Today - Please Check And Follow Up"],
    // program_expiry: [
    //   "Clients Getting Dropout Today (Please Extend Expiry Date As Per Pending Session.)",
    // ],
  },

  birthday_hamper_not_claimed: {
    pending_today: ["Birthday Today (Hamper Not Claimed)"],
    pending_yesterday: ["Birthday Yesterday (Hamper Not Claimed)"],
    pending_day_before_yesterday: [
      "Birthday Day Before Yesterday (Hamper Not Claimed)",
    ],
  },
  lead_app: {
    overall_pending: ["Lead Latest App (App Intro Welcome Call Pending)"],
    today: ["Lead Latest App (App Intro Welcome Call Pending) - Today"],
  },
  oc_app: {
    overall_pending: ["OC Latest App (App Intro Welcome Call Pending)"],
    today: ["OC Latest App (App Intro Welcome Call Pending) - Today"],
  },
  overdue: {
    balance_od: ["Balance Overdue"],
    on_hold_od: ["Onhold - Overdue Latest First"],
    "advance_purchase_od (active)": [
      "Advance purchase OD with Active Program (Only Special Stack Included)",
    ],
    "advance_purchase_od (not active)": [
      "Advance purchase OD without Active Program (Only Special Stack Included)",
    ],
    dormancy_19th_day_plus: ["Dormancy - 19th Day +"],
    assessment_not_filled: ["Assessment Not Filled Clients"],
    weight_od: [
      "Dormancy - 10 Day OD (11th - 12th )",
      "Dormancy - Level 1 (13th - 14th)",
      "Dormancy - Level 2 (15th - 16th)",
      "Dormancy - Level 3 (16th - 17th)",
    ],
    not_started_od: ["Not Started Client Overdue Latest First"],
    "feedback_od_(Ht_&_Te)": [
      "Half Time Feedback First Day",
      "Half Time Feedback Day 2 (OD)",
      "Half Time Feedback Day 3 (OD)",
      "Half Time Feedback Day 4 (OD)",
      "Half Time Feedback Day 5 (OD)",
      "Tailend Feedback First Day",
      "Tailend Feedback Day 2 (OD)",
      "Tailend Feedback Day 3 (OD)",
      "Tailend Feedback Day 4 (OD)",
      "Tailend Feedback Day 5 (OD)",
    ],
    "health_score_od_(Ht_&_Te)": [
      "Half Time Health Score First Day",
      "Half Time Health Score Day 2 (OD)",
      "Half Time Health Score Day 3 (OD)",
      "Half Time Health Score Day 4 (OD)",
      "Half Time Health Score Day 5 (OD)",
      "Tailend Health Score First Day",
      "Tailend Health Score Day 2 (OD)",
      "Tailend Health Score Day 3 (OD)",
      "Tailend Health Score Day 4 (OD)",
      "Tailend Health Score Day 5 (OD)",
    ],
    call_od: [
      "Tailend Feedback Call First Day",
      "Tailend Feedback Call Day 2 (OD)",
      "Tailend Feedback Call Day 3 (OD)",
      "Tailend Feedback Call Day 4 (OD)",
      "Tailend Feedback Call Day 5 (OD)",
    ],
    goal_od: [
      "Tailend Goal First Day",
      "Tailend Goal Call Day 2 (OD)",
      "Tailend Goal Call Day 3 (OD)",
      "Tailend Goal Call Day 4 (OD)",
      "Tailend Goal Call Day 5 (OD)",
    ],
  },
};

export const genderCodeMapping = {
  1: "Male",
  2: "Female",
  0: "Other",
};

export const PREGNANCY_NOTIFICATIONS = {
  1: [
    { id: 805, isGuideActivation: false }, // Managing nausea in early pregnancy
    { id: 806, isGuideActivation: false }, // Feeling a little low on energy?
    { id: 807, isGuideActivation: false }, // Your body’s cues may change
    { id: 808, isGuideActivation: false }, // Do you have any reports or doctor updates?
    { id: 809, isGuideActivation: false }, // What to expect in your first trimester
  ],

  2: [
    { id: 907, isGuideActivation: true }, // Trimester 2 Guide is now active
    { id: 908, isGuideActivation: false }, // Foods that support your baby’s growth
    { id: 909, isGuideActivation: false }, // Keeping digestion smooth
    { id: 910, isGuideActivation: false }, // Noticing new changes in your body?
  ],

  3: [
    { id: 911, isGuideActivation: true }, // Trimester 3 Guide is now live
    { id: 912, isGuideActivation: false }, // Staying comfortable in your third trimester
    { id: 913, isGuideActivation: false }, // Managing heartburn gently
    { id: 914, isGuideActivation: false }, // Helping you stay comfortable
    { id: 915, isGuideActivation: false }, // Trouble sleeping lately?
  ],
};

export const drStoreWeighingScaleHamperItems = [
  {
    quantity: 1,
    product_slug: "bn-bodyscan-smart-scale",
    product_sku: "BN-DR-1",
  },
];

export const SMART_SCALE_PRICE_TO_BN = 908.6;
export const SMART_SCALE_PRICE = 1299;

export const marketingVideoUrls = [
  {
    video_link:
      "https://res.cloudinary.com/dg4wzx8c8/video/upload/v1771572425/IMG_8532_o4ys44.mp4",
    product_link: "https://balancenutrition.in/shop",
  },
  {
    video_link:
      "https://res.cloudinary.com/dg4wzx8c8/video/upload/v1771572075/IMG_8525_evau38.mp4",
    product_link:
      "https://balancenutrition.in/shop/bn-chocolate-whey-protein-isolate",
  },
  {
    video_link:
      "https://res.cloudinary.com/dg4wzx8c8/video/upload/v1771572277/IMG_8667_ft9lm9.mp4",
    product_link: "https://balancenutrition.in/shop/dessert-cookies-chocolate",
  },
];
