import { Router } from "express";
const router = Router();
import userRoutes from "./userRoutes.js";
import recipeRoutes from "./recipeRoutes.js";
import categoryRoutes from "./categoryRoutes.js";
import subCategoryRoutes from "./subCategoryRoutes.js";
import cuisineRoutes from "./cuisineRoutes.js";
import successStoriesRoutes from "./succesStoriesRoutes.js";
import recipeTypeRoutes from "./recipeTypeRoutes.js";
import blogsPostRoutes from "./blogsPostRoutes.js";
import fbPostRoutes from "./fbPostRoutes.js";
import instaPostRoutes from "./instaPostRoutes.js";
import offerRoutes from "./offerRoutes.js";
import hashtagRoutes from "./hashtagRoutes.js";
import programMasterRoutes from "./programMasterRoutes.js";
import programSessionRoutes from "./programSessionRoutes.js";
import draftRoutes from "./draftsRoutes.js";
import healthIssuesRoutes from "./healthIssuesRoutes.js";
import locationRoutes from "./locationRoutes.js";
import notificationRoutes from "./notificationRoutes.js";
import scheduleNotificationRoutes from "./scheduledNotificationsRoutes.js";
import rawVideosRoutes from "./rawVideosRoutes.js";
import dashboardRoutes from "./dashboardRoutes.js";
import otherLinksRoutes from "./otherLinksRoutes.js";
import clientDetailsRoutes from "./clientRoutes.js";
import blogCategoryRoutes from "./blogCatsRoutes.js";
import searchRoutes from "./searchRoute.js";
import imageSearchRoutes from "./imageSearchRoutes.js";
import watiRoutes from "./watiRoutes.js";
import goodMailRoutes from "./goodMailRoutes.js";
import socialPostRoutes from "./socialPostRoutes.js";
import userSearchLogsRoutes from "./userSearchLogRoutes.js";
import programOfferImagesRoutes from "./programOfferImageRoutes.js";
import programStatsImagesRoutes from "./programStatsImageRoutes.js";
import specialDietPlanRoutes from "./specialDietPlanRoutes.js";
import tableTextRoutes from "./tableTextRoutes.js";
import ingredientsRoutes from "./ingredientRoutes.js";
import shortUrlRoutes from "./shortUrlRoutes.js";
import contentRoutes from "./contentRoutes.js";
import khyatisContentRoutes from "./khyatisContentRoutes.js";
import programDocumentRoutes from "./programDocumentRoutes.js";

router.use("/user", userRoutes);
router.use("/recipe", recipeRoutes);
router.use("/category", categoryRoutes);
router.use("/sub-category", subCategoryRoutes);
router.use("/cuisine", cuisineRoutes);
router.use("/success-stories", successStoriesRoutes);
router.use("/recipe-type", recipeTypeRoutes);
router.use("/health-reads", blogsPostRoutes);
router.use("/fb-posts", fbPostRoutes);
router.use("/insta-posts", instaPostRoutes);
router.use("/offers", offerRoutes);
router.use("/hashtags", hashtagRoutes);
router.use("/program", programMasterRoutes);
router.use("/program-session", programSessionRoutes);
router.use("/drafts", draftRoutes);
router.use("/health-issues", healthIssuesRoutes);
router.use("/location", locationRoutes);
router.use("/notifications", notificationRoutes);
router.use("/schedule-notifications", scheduleNotificationRoutes);
router.use("/raw-videos", rawVideosRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/other-links", otherLinksRoutes);
router.use("/client-details", clientDetailsRoutes);
router.use("/blog-category", blogCategoryRoutes);
router.use("/search", searchRoutes);
router.use("/ies", imageSearchRoutes);
router.use("/wati", watiRoutes);
router.use("/good-mails", goodMailRoutes);
router.use("/social-posts", socialPostRoutes);
router.use("/search-logs", userSearchLogsRoutes);
router.use("/program-offers", programOfferImagesRoutes);
router.use("/program-stats", programStatsImagesRoutes);
router.use("/ingredients", ingredientsRoutes);
router.use("/special-diet-plan", specialDietPlanRoutes);
router.use("/table-text", tableTextRoutes);
router.use("/short-url", shortUrlRoutes);
router.use("/content", contentRoutes);
router.use("/khyatis-content", khyatisContentRoutes);
router.use("/program-documents", programDocumentRoutes);
export default router;
